######################################################################
# Automatically generated by qmake (3.0) Mon Feb 26 11:07:24 2018
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT+=widgets